### ISSUE TITLE
Error message when using -a Option

### ISSUE THREAD

**Issue by rflgrt** [deadc0de6/gocatcli#1]
When trying to index with the -a (archive) Option on Ubuntu 23.10 I get the following error message:

panic: interface conversion: archiver.Gz is not archiver.Extractor: missing method Extract

I used the binary of the v1.0 release (gocatcli_Linux_x86_64.tar.gz) 

Thanks a lot for developing this really useful tool!

Best wishes

**Comment by deadc0de6** [comment]
Thanks for your support!
It was a bug in the way I was handling the gzip'ed files.
It is fixed with above commit and I'll release a new version shortly.

**Comment by deadc0de6** [comment]
New version [v1.0.1](https://github.com/deadc0de6/gocatcli/releases/tag/v1.0.1) has been released with the fix. Thanks for your help on this.
