### ISSUE TITLE
gocatcli tree swallows nested directories with identical name

### ISSUE THREAD

**Issue by rflgrt** [deadc0de6/gocatcli#3]
I am using v1.0.1 on Ubuntu 23.10 and noticed the following behaviour:
When subdirectories of identical names are nested, one of the directories is "forgotten"

In `gocatcli` tree my directory looks as follows

```
 ├─┬artist                 
 │ ├──01 - my_song.flac
 │ ├──02 - my_song.flac
 │ ├──second album    
```
instead of
```
 ├─┬artist 
 │ ├──artist                
 │ │   ├──01 - my_song.flac
 │ │   ├──02 - my_song.flac
 │ ├──second album    
```

This is also true for `gocatcli ls`

**Comment by rflgrt** [comment]
The newer version v1.0.2 shows the same behaviour. The catalog-file looks ok, seems a problem when reading the file or with output.

**Comment by deadc0de6** [comment]
Ouch that's a nasty bug. Thanks for reporting it!
I identified the bug and will push a fix ASAP

**Comment by deadc0de6** [comment]
New [version 1.0.3](https://github.com/deadc0de6/gocatcli/releases/tag/v1.0.3) has been released with the bug fixed.
