### ISSUE TITLE
Add AUR package

### ISSUE THREAD

**Issue by deathtrip** [deadc0de6/gocatcli#5]
I noticed that on the catcli-git AUR package, there's no notice that it's been superseded by gocatcli. Users might think the app has been abandoned, cause not everybody checks the github repos. I think adding gocatcli to the AUR and making a sticky comment on the catcli-git page would be a good idea.

**Comment by deadc0de6** [comment]
Good point, I'll do that, thanks for the heads-up

**Comment by deadc0de6** [comment]
@deathtrip gocatcli is now available on aur under [gocatcli-git](https://aur.archlinux.org/packages/gocatcli-git). Thanks for the hint!
